server:
  port: 8080
management:
  server:
    port: 9080
    address: 127.0.0.1
spring:
  data:
    mongodb:
      host: 0.0.0.0
      database: bootcamp
      port: '27017'
      username: root
      password: rootpassword
