server:
  port: 8080
  address: 10.0.0.69
management:
  server:
    port: 9080
    address: 127.0.0.1
spring:
  data:
    mongodb:
      uri: mongodb+srv://proy-1-user:nmIhMdQdCd5lPAcN@cluster0.clihz.mongodb.net/bootcamp-project?retryWrites=true&w=majority
