server:
  port: 8080
management:
  server:
    port: 9080
    address: 127.0.0.1
spring:
  data:
    mongodb:
      database: bootcamp
      port: '27017'
      host: localhost
      user: root
      password: rootpassword
