server:
  port: 8083
management:
  server:
    port: 9083
    address: 127.0.0.1
spring:
  data:
    mongodb:
      host: localhost
      database: bootcamp
      port: '27017'
      username: root
      password: rootpassword
